language: node_js
addons:
  apt:
    packages:
      - libgconf-2-4
node_js:
  - "10"
cache:
  yarn: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
notifications:
  email: false
